package other.sumur.stock.test.others;

import java.util.Date;

public class ImMessageControl{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_message_control.uid
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_message_control.subject
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_message_control.device
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    private Integer device;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_message_control.version
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_message_control.type
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_message_control.send_show
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    private Integer sendShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_message_control.send_body
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    private Integer sendBody;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_message_control.send_message
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    private String sendMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_message_control.receive_show
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    private Integer receiveShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_message_control.receive_message
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    private String receiveMessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_message_control.is_save
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    private Integer isSave;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_message_control.is_show
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    private Integer isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_message_control.add_list
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    private Integer addList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_message_control.is_service
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    private Integer isService;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_message_control.is_interval
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    private Integer isInterval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_message_control.is_offline
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    private Integer isOffline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_message_control.is_push
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    private Integer isPush;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_message_control.create_date
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_message_control.remarks
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_message_control.uid
     *
     * @return the value of im_message_control.uid
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_message_control.uid
     *
     * @param uid the value for im_message_control.uid
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_message_control.subject
     *
     * @return the value of im_message_control.subject
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_message_control.subject
     *
     * @param subject the value for im_message_control.subject
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_message_control.device
     *
     * @return the value of im_message_control.device
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public Integer getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_message_control.device
     *
     * @param device the value for im_message_control.device
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public void setDevice(Integer device) {
        this.device = device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_message_control.version
     *
     * @return the value of im_message_control.version
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_message_control.version
     *
     * @param version the value for im_message_control.version
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_message_control.type
     *
     * @return the value of im_message_control.type
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_message_control.type
     *
     * @param type the value for im_message_control.type
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_message_control.send_show
     *
     * @return the value of im_message_control.send_show
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public Integer getSendShow() {
        return sendShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_message_control.send_show
     *
     * @param sendShow the value for im_message_control.send_show
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public void setSendShow(Integer sendShow) {
        this.sendShow = sendShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_message_control.send_body
     *
     * @return the value of im_message_control.send_body
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public Integer getSendBody() {
        return sendBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_message_control.send_body
     *
     * @param sendBody the value for im_message_control.send_body
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public void setSendBody(Integer sendBody) {
        this.sendBody = sendBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_message_control.send_message
     *
     * @return the value of im_message_control.send_message
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public String getSendMessage() {
        return sendMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_message_control.send_message
     *
     * @param sendMessage the value for im_message_control.send_message
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public void setSendMessage(String sendMessage) {
        this.sendMessage = sendMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_message_control.receive_show
     *
     * @return the value of im_message_control.receive_show
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public Integer getReceiveShow() {
        return receiveShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_message_control.receive_show
     *
     * @param receiveShow the value for im_message_control.receive_show
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public void setReceiveShow(Integer receiveShow) {
        this.receiveShow = receiveShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_message_control.receive_message
     *
     * @return the value of im_message_control.receive_message
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public String getReceiveMessage() {
        return receiveMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_message_control.receive_message
     *
     * @param receiveMessage the value for im_message_control.receive_message
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public void setReceiveMessage(String receiveMessage) {
        this.receiveMessage = receiveMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_message_control.is_save
     *
     * @return the value of im_message_control.is_save
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public Integer getIsSave() {
        return isSave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_message_control.is_save
     *
     * @param isSave the value for im_message_control.is_save
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public void setIsSave(Integer isSave) {
        this.isSave = isSave;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_message_control.is_show
     *
     * @return the value of im_message_control.is_show
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public Integer getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_message_control.is_show
     *
     * @param isShow the value for im_message_control.is_show
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public void setIsShow(Integer isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_message_control.add_list
     *
     * @return the value of im_message_control.add_list
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public Integer getAddList() {
        return addList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_message_control.add_list
     *
     * @param addList the value for im_message_control.add_list
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public void setAddList(Integer addList) {
        this.addList = addList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_message_control.is_service
     *
     * @return the value of im_message_control.is_service
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public Integer getIsService() {
        return isService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_message_control.is_service
     *
     * @param isService the value for im_message_control.is_service
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public void setIsService(Integer isService) {
        this.isService = isService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_message_control.is_interval
     *
     * @return the value of im_message_control.is_interval
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public Integer getIsInterval() {
        return isInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_message_control.is_interval
     *
     * @param isInterval the value for im_message_control.is_interval
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public void setIsInterval(Integer isInterval) {
        this.isInterval = isInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_message_control.is_offline
     *
     * @return the value of im_message_control.is_offline
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public Integer getIsOffline() {
        return isOffline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_message_control.is_offline
     *
     * @param isOffline the value for im_message_control.is_offline
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public void setIsOffline(Integer isOffline) {
        this.isOffline = isOffline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_message_control.is_push
     *
     * @return the value of im_message_control.is_push
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public Integer getIsPush() {
        return isPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_message_control.is_push
     *
     * @param isPush the value for im_message_control.is_push
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public void setIsPush(Integer isPush) {
        this.isPush = isPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_message_control.create_date
     *
     * @return the value of im_message_control.create_date
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_message_control.create_date
     *
     * @param createDate the value for im_message_control.create_date
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_message_control.remarks
     *
     * @return the value of im_message_control.remarks
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_message_control.remarks
     *
     * @param remarks the value for im_message_control.remarks
     *
     * @mbggenerated Tue Aug 25 18:32:43 CST 2015
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
}